#!/bin/bash
#set -v

output(){
    local -i max=$1
    local sec=$2
    local string=$3
    for (( count=0; count<max; count++)); do
        printf "$string\n"
        sleep "$sec"
    done 
}

for ((n=0;n<2;n++)); do

    for ((i=0;i<3;i++)); do
        output 12 .3 "Badgers"
        output 2 1 "Mushrooms"
    done

    ((n<2)) && output 1 1.5 "Big Snake" # short circuit logic
    

done
