#!/bin/sh

# Fun nod to python

echo "Answer me these questions three, 'ere the other side ye see':"

echo "What is your name"

read -r name

echo "What is your quest"

case $name in
    "Sir Robin")
        echo "What is your capital of Assyria?"
        ;;
    "Sir Lancelot")
        echo "What is your favorite colour?"
        ;;
    "King Arthur")
        echo "What is the air speed velocity of an unladen swallow?"
        echo "How do you know so much about swallows?"
        echo "Well, as a King you have to know these things you know."
        ;;
    *)
        echo "Killer Bunny"
esac

