#!/bin/bash

# Fun nod to python
# set -x 
printf "Answer me these questions three, 'ere the other side ye see':\n"

printf "What is your name\n"

read -r name

printf "What is your quest\n"


case ${name,,} in
    "robin")
        printf "What is your capital of Assyria?\n"
        ;;
    "lancelot")
        printf "What is your favorite colour?\n"
        ;;
    "arthur")
        printf "What is the air speed velocity of an unladen swallow?\n"
        printf "How do you know so much about swallows?\n"
        printf "Well, as a King you have to know these things you know.\n"
        ;;
    *)
        printf "Killer Bunny\n"
        ;;
esac

# Look at adding color and practicing 
